### ISSUE TITLE
Peer Review 01

### ISSUE THREAD

**Issue by dy-lin** [STAT545-UBC-hw-2019-20/stat545-hw-mdabdullahkafi#1]
Peer-Review HW-01 for Mohammad Abdullah heel Kafi
----------------------------------------------------
Topic                       | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style**            | :heavy_check_mark: |  |  |
**Coding strategy**         |  | :heavy_check_mark: |  |
**Presentation: graphs**    |  |  :heavy_check_mark:|  |
**Presentation: tables**    |  | :heavy_check_mark:  |  |
**Achievement, creativity** | :heavy_check_mark: |  |  |
**Ease of access**          | | :heavy_check_mark: |  |

# Remarks:

#### Specific Praise
- I really liked the introduction to the Gapminder dataset. It really brings the assignment together with better flow
- I think you did a great job of 'narrating' the assignment. I like the comments and observations about the analysis. It makes your assignment really easy to follow.

#### Elaborating on above / Specific Constructive Criticism
- **Presentation: graphs, coding strategy**: In the knit form `html`, you cannot see the code used to generate any of your plots-- I would personally include this so everyone can see any previous processing of the data (filtering, etc.) that was done before plotting (I can however see this in the `Rmd` file)-- I would suggest that next time you leave out the `echo = FALSE` statement
- **Ease of access**: Just looking at the knitted `html`, I cannot tell whether or not you used functions we were taught in class -- the only one that is obviously used is `summary()`, although looking through the `Rmd` file, I can see that you used the functions -- same suggestion as the point above
- **Presentation: tables**: I'm not sure if it was just how it rendered on my computer, but your slides had some tables that were cut off, and some overlapping text (see screenshots below)
![Screen Shot 2019-09-23 at 9 48 47 AM](https://user-images.githubusercontent.com/44071582/65446495-5d10a080-dde9-11e9-90b5-46c3a50f6615.png)
![Screen Shot 2019-09-23 at 9 49 02 AM](https://user-images.githubusercontent.com/44071582/65446496-5d10a080-dde9-11e9-84fc-35f6d5341ec8.png)
![Screen Shot 2019-09-23 at 9 49 18 AM](https://user-images.githubusercontent.com/44071582/65446497-5d10a080-dde9-11e9-8975-cfcba6b1df43.png)
![Screen Shot 2019-09-23 at 9 49 36 AM](https://user-images.githubusercontent.com/44071582/65446498-5d10a080-dde9-11e9-8e7b-a1395e42f358.png)
- In the above points, I have selected **satisfactory** as opposed to **needs work** since these instances only occur in rendering the slides, and not your `html_document`, which was perfectly fine

#### Something I Struggled With
- **Ease of access**: To view your knit `html` file, I used [GitHub HTML Preview](https://htmlpreview.github.io), where your file can be viewed as such [here](https://github.com/STAT545-UBC-hw-2019-20/stat545-hw-mdabdullahkafi/blob/master/Assignment%2001/hw01_gapminder_data_exploration.html).
- **Ease of access**: However, using this method, I can't seem to view your slides in `html` [here](https://htmlpreview.github.io/?https://github.com/STAT545-UBC-hw-2019-20/stat545-hw-mdabdullahkafi/blob/master/Assignment%2001/hw01_gapminder_data_slides.html)
- **Ease of access**: Like the instructors said, it might've been helpful to knit to `pdf` or a `github_document` so the end result could be viewed directly in GitHub -- I would recommend this for the next assignment
- I had to download your `html` slides file in order to view them
- **Ease of access**: I understand that since it wasn't required, it meant more unnecessary work, but it does make it easier for the person evaluating your assignment (even I almost didn't knit to `pdf` because it kept interfering with the slide formatting)

#### What I Learned
- In my assignment, I mostly did exactly what the assignment was asking and nothing more, but I learned that I should also do as you did and add commentary and observations, and make the assignment flow better and easier to follow for the evaluators

**Comment by mdabdullahkafi** [comment]
Thank you for your `constructive feedback. Really impressive.  I will try my label best to overcome all the shortcomings.
